sudo: required

language: java

services:
- docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
- tar xvf deployment_keys.tar
- chmod +x gradlew

install:
- "./gradlew build jacocoTestReport --scan -PpatchVersion=$TRAVIS_BUILD_NUMBER"

after_success:
- bash <(curl -s https://codecov.io/bash)

before_script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- eval "__SSH_AGENT_S__"
- chmod 600 deployment_keys/deploy_test
- ssh-add deployment_keys/deploy_test
- chmod 600 deployment_keys/deploy_prod
- ssh-add deployment_keys/deploy_prod

script:
- export DOCKER_REPO=${dockerhubOrganization}/${dockerhubRepository}
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr '/' '-' ; fi`
- export TAG_VERSION=`cat VERSION`.$TRAVIS_BUILD_NUMBER
- docker build -t $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER .
- docker tag $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TAG
- docker tag $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TAG_VERSION
- docker push $DOCKER_REPO
- if [ "$TRAVIS_BRANCH" == "develop" ]; then ssh -o "StrictHostKeyChecking no" "$DEPLOY_TEST_USER"@"$DEPLOY_TEST_HOST" TAG_TO_DEPLOY=$TAG_VERSION ENVIRONMENT_NAME=test LOGZIO_TOKEN=$LOGZIO_TOKEN 'bash -s' < src/main/scripts/deploy.sh; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then ssh -o "StrictHostKeyChecking no" "$DEPLOY_PROD_USER"@"$DEPLOY_PROD_HOST" TAG_TO_DEPLOY=$TAG_VERSION ENVIRONMENT_NAME=prod LOGZIO_TOKEN=$LOGZIO_TOKEN 'bash -s' < src/main/scripts/deploy.sh; fi

env:
  global:
  - secure: $DOCKER_USERNAME # DOCKER_USERNAME
  - secure: $DOCKER_PASSWORD # DOCKER_PASSWORD
  - secure: $DEPLOY_TEST_USER # DEPLOY_TEST_USER
  - secure: $DEPLOY_TEST_HOST # DEPLOY_TEST_HOST
  - secure: $DEPLOY_PROD_USER # DEPLOY_PROD_USER
  - secure: $DEPLOY_PROD_HOST # DEPLOY_PROD_HOST
  - secure: $LOGZIO_TOKEN # LOGZIO_TOKEN
